# syntax=docker/dockerfile:1


ARG NODE_VERSION=20.15.0

FROM node:${NODE_VERSION}-alpine as base

RUN apk add --no-cache bash

# Set working directory for all build stages.
WORKDIR /app

FROM base as deps

FROM deps as build

ENV NODE_ENV production

COPY --chown=node:node ./dist ./dist
COPY --chown=node:node docker.env ./.env
COPY --chown=node:node package.json ./

RUN npm install


USER node


EXPOSE 3000
CMD npm start

